"""Modifying data model

Revision ID: 1866064b6ca3
Revises: c83be8ff7050
Create Date: 2024-05-05 12:38:01.796971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1866064b6ca3'
down_revision: Union[str, None] = 'c83be8ff7050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_profile_strategy', sa.Column('total_profitability', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('volatility', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('maximum_loss', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('sharpe', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('sortino', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('alpha', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('beta', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('information_ratio', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('success_rate', sa.Numeric(), nullable=True))
    op.add_column('investment_profile_strategy', sa.Column('portfolio_concentration_ratio', sa.Numeric(), nullable=True))
    op.drop_column('strategy', 'Maximum_loss')
    op.drop_column('strategy', 'Volatility')
    op.drop_column('strategy', 'Sortino')
    op.drop_column('strategy', 'Sharpe')
    op.drop_column('strategy', 'Information_ratio')
    op.drop_column('strategy', 'Total_profitability')
    op.drop_column('strategy', 'Alpha')
    op.drop_column('strategy', 'Beta')
    op.drop_column('strategy', 'Portfolio_concentration_ratio')
    op.drop_column('strategy', 'Success_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('Success_rate', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Portfolio_concentration_ratio', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Beta', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Alpha', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Total_profitability', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Information_ratio', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Sharpe', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Sortino', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Volatility', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('Maximum_loss', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('investment_profile_strategy', 'portfolio_concentration_ratio')
    op.drop_column('investment_profile_strategy', 'success_rate')
    op.drop_column('investment_profile_strategy', 'information_ratio')
    op.drop_column('investment_profile_strategy', 'beta')
    op.drop_column('investment_profile_strategy', 'alpha')
    op.drop_column('investment_profile_strategy', 'sortino')
    op.drop_column('investment_profile_strategy', 'sharpe')
    op.drop_column('investment_profile_strategy', 'maximum_loss')
    op.drop_column('investment_profile_strategy', 'volatility')
    op.drop_column('investment_profile_strategy', 'total_profitability')
    # ### end Alembic commands ###
