"""Correcting relationship between user and investment profile

Revision ID: 2ae32eacfe47
Revises: b0d480181c4f
Create Date: 2024-03-09 21:04:43.481379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae32eacfe47'
down_revision: Union[str, None] = 'b0d480181c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
