"""New investmentStrategyProfile field. Annual return

Revision ID: 6090006ea208
Revises: dd5fcf669733
Create Date: 2024-06-24 20:08:01.854421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6090006ea208'
down_revision: Union[str, None] = 'dd5fcf669733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_profile_name', 'investment_profile', ['user_id', 'name'])
    op.add_column('investment_profile_strategy', sa.Column('annual_return', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_profile_strategy', 'annual_return')
    op.drop_constraint('unique_user_profile_name', 'investment_profile', type_='unique')
    # ### end Alembic commands ###
