"""Increased the size of the password hash

Revision ID: 64ae1d94bf7c
Revises: 8fd973e8079b
Create Date: 2024-03-09 23:21:44.704580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ae1d94bf7c'
down_revision: Union[str, None] = '8fd973e8079b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###
