"""Updating relationship between investment-profile and investment-profile-strategy

Revision ID: 6994b98d2ef9
Revises: 802e10aa83f9
Create Date: 2024-06-15 19:56:45.028477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6994b98d2ef9'
down_revision: Union[str, None] = '802e10aa83f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
