"""Fixing the models

Revision ID: 7fd15ece5ed9
Revises: 64ae1d94bf7c
Create Date: 2024-03-17 19:51:30.068688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd15ece5ed9'
down_revision: Union[str, None] = '64ae1d94bf7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_profile', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('investment_profile_id_user_fkey', 'investment_profile', type_='foreignkey')
    op.create_foreign_key(None, 'investment_profile', 'user', ['user_id'], ['id'])
    op.drop_column('investment_profile', 'id_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_profile', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'investment_profile', type_='foreignkey')
    op.create_foreign_key('investment_profile_id_user_fkey', 'investment_profile', 'user', ['id_user'], ['id'], ondelete='CASCADE')
    op.drop_column('investment_profile', 'user_id')
    # ### end Alembic commands ###
