"""Updating relationship betweem investment-profile and investment-profile-strategy

Revision ID: 802e10aa83f9
Revises: 950f63e483c3
Create Date: 2024-06-15 19:48:13.860392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802e10aa83f9'
down_revision: Union[str, None] = '950f63e483c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'investment_profile_strategy', 'investment_profile', ['investment_profile_id'], ['id'])
    op.create_foreign_key(None, 'investment_profile_strategy', 'strategy', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investment_profile_strategy', type_='foreignkey')
    op.drop_constraint(None, 'investment_profile_strategy', type_='foreignkey')
    # ### end Alembic commands ###
