"""Updating operation table

Revision ID: 80cecb929c01
Revises: b1bef13dddb8
Create Date: 2024-06-13 18:19:02.756386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cecb929c01'
down_revision: Union[str, None] = 'b1bef13dddb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('price', sa.Numeric(), nullable=True))
    op.drop_column('operation', 'profit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('profit', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('operation', 'price')
    # ### end Alembic commands ###
