"""Updating Strategy model

Revision ID: 85d2d9da74b3
Revises: 1866064b6ca3
Create Date: 2024-05-13 20:50:28.623558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d2d9da74b3'
down_revision: Union[str, None] = '1866064b6ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'model')
    # ### end Alembic commands ###
