"""New column validated in investment_profile_strategy

Revision ID: a0881f5a54e4
Revises: 85d2d9da74b3
Create Date: 2024-05-23 20:08:19.573017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0881f5a54e4'
down_revision: Union[str, None] = '85d2d9da74b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_profile_strategy', sa.Column('validated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_profile_strategy', 'validated')
    # ### end Alembic commands ###
