"""Table operation modified

Revision ID: a9ce954c349e
Revises: a0881f5a54e4
Create Date: 2024-05-26 21:07:26.187327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ce954c349e'
down_revision: Union[str, None] = 'a0881f5a54e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('id_profile', sa.Integer(), nullable=True))
    op.add_column('operation', sa.Column('total', sa.Numeric(), nullable=True))
    op.create_foreign_key(None, 'operation', 'investment_profile', ['id_profile'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.drop_column('operation', 'total')
    op.drop_column('operation', 'id_profile')
    # ### end Alembic commands ###
