"""Initial Migration

Revision ID: b0d480181c4f
Revises: 
Create Date: 2024-03-09 19:50:05.370008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d480181c4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('Total_profitability', sa.Numeric(), nullable=True),
    sa.Column('Volatility', sa.Numeric(), nullable=True),
    sa.Column('Maximum_loss', sa.Numeric(), nullable=True),
    sa.Column('Sharpe', sa.Numeric(), nullable=True),
    sa.Column('Sortino', sa.Numeric(), nullable=True),
    sa.Column('Alpha', sa.Numeric(), nullable=True),
    sa.Column('Beta', sa.Numeric(), nullable=True),
    sa.Column('Information_ratio', sa.Numeric(), nullable=True),
    sa.Column('Success_rate', sa.Numeric(), nullable=True),
    sa.Column('Portfolio_concentration_ratio', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('initial_capital', sa.Numeric(), nullable=True),
    sa.Column('duracion', sa.Date(), nullable=True),
    sa.Column('monthly_contribution', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_strategy', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Numeric(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_strategy'], ['strategy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_profile_strategy',
    sa.Column('investment_profile_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investment_profile_id'], ['investment_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investment_profile_id', 'strategy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_profile_strategy')
    op.drop_table('operation')
    op.drop_table('investment_profile')
    op.drop_table('user')
    op.drop_table('strategy')
    # ### end Alembic commands ###
