"""Updating relationship between investment-profile and investment-profile-strategy 2

Revision ID: dd5fcf669733
Revises: 6994b98d2ef9
Create Date: 2024-06-15 20:10:49.759424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5fcf669733'
down_revision: Union[str, None] = '6994b98d2ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
